# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdb2c8b80b03020355c3ec5151a69353b17d67de8197e575e2b9a23da4261ac919b16a14aa2ec870e34fdbb279b3916afc6320f10baeb73895caa284584f56e3

test:
  secret_key_base: 2d10189575e37feddd497bc34c69e29845b9a5b3adbce8e234cb2b7118d218724528569176cdedcdb132af0525ded7568c4a27331edcfeae814536429908de20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
